export const students = [
	{ name: 'Sofi Baazov', photo: "https://oldough.com/static/images/avatar.png", bio: null, cvLink: null },
	{ name: 'Anna Fridman', photo: "https://oldough.com/static/images/avatar.png", bio: null, cvLink: null },
	{ name: 'Deadrop Furman', photo: "https://oldough.com/static/images/avatar.png", bio: null, cvLink: null },
	{ name: 'Leonid Garchu', photo: "https://oldough.com/static/images/avatar.png", bio: null, cvLink: null },
	{ name: 'Shay Geva', photo: "https://oldough.com/static/images/avatar.png", bio: null, cvLink: null },
	{ name: 'Uri Koffman', photo: "https://oldough.com/static/images/avatar.png", bio: null, cvLink: null },
	{ name: 'Ana Levit', photo: 'ana-levit/photo.jfif', bio: null, cvLink: 'ana-levit/index.html' },
	{ name: 'Effi Malach', photo: "https://oldough.com/static/images/avatar.png", bio: null, cvLink: null },
	{ name: 'Haitham Mansour', photo: "https://oldough.com/static/images/avatar.png", bio: null, cvLink: null },
	{ name: 'Yakov Markman', photo: "https://oldough.com/static/images/avatar.png", bio: null, cvLink: null },
	{ name: 'Kobi Mechani', photo: "https://oldough.com/static/images/avatar.png", bio: null, cvLink: null },
	{ name: 'Omer Messing', photo: "https://oldough.com/static/images/avatar.png", bio: null, cvLink: null },
	{ name: 'Nivo music', photo: "https://oldough.com/static/images/avatar.png", bio: null, cvLink: null },
	{ name: 'Barak Ostroumov', photo: "https://oldough.com/static/images/avatar.png", bio: null, cvLink: null },
	{ name: 'Areen Shalli', photo: "https://oldough.com/static/images/avatar.png", bio: null, cvLink: null },
	// { name: 'Tal Sprung', photo: "https://oldough.com/static/images/avatar.png", bio: null, cvLink: null },
];
