export const students = [
	{ name: 'Sofi Baazov', photo: null, bio: null, cvLink: null },
	{ name: 'Anna Fridman', photo: null, bio: null, cvLink: null },
	{ name: 'Deadrop Furman', photo: null, bio: null, cvLink: null },
	{ name: 'Leonid Garchu', photo: null, bio: null, cvLink: null },
	{ name: 'Shay Geva', photo: null, bio: null, cvLink: null },
	{ name: 'Uri Koffman', photo: null, bio: null, cvLink: null },
	{ name: 'Ana Levit', photo: 'ana-levit/photo.jfif', bio: "Electrical and Electronics Engineer", cvLink: 'ana-levit/index.html' },
	{ name: 'Effi Malach', photo: null, bio: null, cvLink: null },
	{ name: 'Haitham Mansour', photo: null, bio: null, cvLink: null },
	{ name: 'Yakov Markman', photo: 'yakov-markman/IMG_8034.jpg', bio: 'Web Developer', cvLink: 'yakov-markman/index.html'},
	{ name: 'Kobi Mechani', photo: null, bio: null, cvLink: null },
	{ name: 'Omer Messing', photo: null, bio: null, cvLink: null },
	{ name: 'Nivo music', photo: null, bio: null, cvLink: null },
	{ name: 'Barak Ostroumov', photo: null, bio: null, cvLink: null },
	{ name: 'Areen Shalli', photo: null, bio: null, cvLink: null },
	{ name: 'Tal Sprung', photo: null, bio: null, cvLink: null },
];
